name: Pulumi
env:
  PULUMI_CONFIG_PASSPHRASE: ""
on:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - '*/README.md'
  workflow_dispatch: {}
jobs:
  kind-clustermesh:
    strategy:
      fail-fast: false
      matrix:
        dir:
          - ./kind-clustermesh-optimization
        clusters:
          - 4
          - 7
          - 10
        connection_mode:
          - "unicast"
          - "bidirectional"
          - "mesh"
    name: Cluster Mesh Kind
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ matrix.dir }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python ✨
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Clean disk
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Install new cilium cli
        run: |
          git clone https://github.com/littlejo/cilium.git
          cd cilium
          git checkout cilium-cli-clustermesh-remote-contexts
          cd cilium-cli
          make
          sudo install -m 0755 -d /usr/local/bin
          sudo install -m 0755 cilium /usr/local/bin

      - name: Installing dependencies 📦️
        run: pip install -r requirements.txt

      - uses: pulumi/actions@v5

      - name: Create stack
        run: pulumi login --local && pulumi stack init dev && pulumi config set --stack dev clusterNumber ${{ matrix.clusters }}

      - uses: pulumi/actions@v5
        with:
          work-dir: ${{ matrix.dir }}
          command: up
          stack-name: dev
          cloud-url: file://~

      - name: Install cilium connection
        run: |
          CONTEXTD="kind-cmesh2"
          CLUSTER_NUMBER=${{ matrix.clusters }}
          CONNECTION_MODE=${{ matrix.connection_mode }}
          for i in $(seq 3 $CLUSTER_NUMBER)
          do
            CONTEXTD=$CONTEXTD,kind-cmesh$i
          done
          echo $CONTEXTD
          cilium clustermesh connect --connection-mode=$CONNECTION_MODE --context=kind-cmesh1 --destination-contexts=$CONTEXTD

      - name: Check Cluster Mesh
        run: |
          CLUSTER_NUMBER=${{ matrix.clusters }}
          for i in $(seq 1 $CLUSTER_NUMBER)
          do
            echo "Cluster: kind-cmesh$i"
            cilium status --context=kind-cmesh$i --wait
            cilium clustermesh status --context=kind-cmesh$i --wait
          done
            echo "Cluster Connectivity test kind-cmesh1 and kind-cmesh2"
          #cilium connectivity test --context kind-cmesh1 --multi-cluster kind-cmesh2

      - name: Delete cilium connection
        run: |
          CONTEXTD="kind-cmesh2"
          CLUSTER_NUMBER=${{ matrix.clusters }}
          CONNECTION_MODE=${{ matrix.connection_mode }}
          for i in $(seq 3 $CLUSTER_NUMBER)
          do
            CONTEXTD=$CONTEXTD,kind-cmesh$i
          done
          echo $CONTEXTD
          cilium clustermesh disconnect --connection-mode=$CONNECTION_MODE --context=kind-cmesh1 --destination-contexts=$CONTEXTD

      - name: Check Cluster Mesh
        run: |
          CLUSTER_NUMBER=${{ matrix.clusters }}
          for i in $(seq 1 $CLUSTER_NUMBER)
          do
            echo "Cluster: kind-cmesh$i"
            cilium status --context=kind-cmesh$i --wait
            cilium clustermesh status --context=kind-cmesh$i --wait
          done
            echo "Cluster Connectivity test kind-cmesh1 and kind-cmesh2"

      - uses: pulumi/actions@v5
        with:
          work-dir: ${{ matrix.dir }}
          command: destroy
          stack-name: dev
          cloud-url: file://~
