name: Pulumi
env:
  PULUMI_CONFIG_PASSPHRASE: ""
on:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - '*/README.md'
jobs:
  kind-clustermesh:
    strategy:
      fail-fast: false
      matrix:
        dir:
          - ./kind-clustermesh
          - ./kind-clustermesh-optimization
        cluster_number:
          - 4
          - 5
    name: Cluster Mesh Kind
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ matrix.dir }}
    steps:
      - uses: actions/checkout@v4
      - uses: cilium/cilium-cli@404d52692f62eebb7211fdacd114848995ada1b7
        with:
          skip-build: true
          release-version: v0.16.10
      - name: Setup Python ✨
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Clean disk
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: Installing dependencies 📦️
        run: pip install -r requirements.txt

      - uses: pulumi/actions@v5

      - name: Create stack
        run: pulumi login --local && pulumi stack init dev && pulumi config set --stack dev clusterNumber $CLUSTER_NUMBER
        env:
          CLUSTER_NUMBER: ${{ matrix.cluster_number }}

      - uses: pulumi/actions@v5
        with:
          work-dir: ${{ matrix.dir }}
          command: up
          stack-name: dev
          cloud-url: file://~

      - name: Check Cluster Mesh
        run: |
          for i in $(seq 1 $CLUSTER_NUMBER)
          do
            echo "Cluster: kind-cmesh$i"
            cilium status --context=kind-cmesh$i --wait
            cilium clustermesh status --context=kind-cmesh$i --wait
          done
            echo "Cluster Connectivity test kind-cmesh1 and kind-cmesh2"
          cilium connectivity test --context kind-cmesh1 --multi-cluster kind-cmesh2

      - uses: pulumi/actions@v5
        with:
          work-dir: ${{ matrix.dir }}
          command: destroy
          stack-name: dev
          cloud-url: file://~
