name: Pulumi
env:
  PULUMI_CONFIG_PASSPHRASE: ""
  CLUSTER_NUMBER: "14"
on:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - '*/README.md'
jobs:
  kind-clustermesh:
    name: Cluster Mesh Kind
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./kind-clustermesh
    steps:
      - uses: actions/checkout@v4
      - uses: cilium/cilium-cli@4892ceb1abbc1f7d8bb5c7f9160ec56717c3c32c
        with:
          skip-build: true
          release-version: v0.16.10

      - name: Clean disk
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: kind deployment
        run: |
          for i in $(seq 1 $CLUSTER_NUMBER)
          do
            sed "s/NUMBER/$i/g" kind.yaml.template > kind-$i.yaml 
            kind create cluster --config kind-$i.yaml --name cmesh$i
          done

      - name: Check Cluster Mesh
        run: |
          for i in $(seq 1 $CLUSTER_NUMBER)
          do
            echo "Cluster: kind-cmesh$i"
            cilium status --context=kind-cmesh$i --wait
            cilium clustermesh status --context=kind-cmesh$i --wait
          done
            echo "Cluster Connectivity test kind-cmesh1 and kind-cmesh2"
          cilium connectivity test --context kind-cmesh1 --multi-cluster kind-cmesh2
