name: Pulumi
env:
  PULUMI_CONFIG_PASSPHRASE: ""
on:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - '*/README.md'
jobs:
  kind-clustermesh:
    strategy:
      fail-fast: false
      matrix:
        dir:
          - ./kind-clustermesh
        clusters:
          - 3
          - 4
          - 5
          - 6
          - 7
          - 8
          - 9
    name: Cluster Mesh Kind
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ${{ matrix.dir }}
    steps:
      - uses: actions/checkout@v4
      - uses: cilium/cilium-cli@404d52692f62eebb7211fdacd114848995ada1b7
        with:
          skip-build: true
          release-version: v0.16.19
      - name: Setup Python ✨
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Clean disk
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: Check Cluster Mesh
        run: |
          version=0.0.7
          wget https://github.com/littlejo/check-cilium-clustermesh/releases/download/v$version/cilium-clustermesh-terratest-$version-linux-amd64.tar.gz
          tar xzvfC cilium-clustermesh-terratest-$version-linux-amd64.tar.gz /usr/local/bin

      - name: Retrieve check scripts
        run: |
          git clone -b improve-code https://github.com/littlejo/check-cilium-clustermesh &

      - name: Installing dependencies 📦️
        run: pip install -r requirements.txt

      - uses: pulumi/actions@v5

      - name: Create stack
        run: pulumi login --local && pulumi stack init dev && pulumi config set --stack dev clusterNumber ${{ matrix.clusters }}

      - uses: pulumi/actions@v5
        with:
          work-dir: ${{ matrix.dir }}
          command: up
          stack-name: dev
          cloud-url: file://~

      - name: Check Cluster Mesh
        run: |
          cd check-cilium-clustermesh/scripts
          bash check-cilium.sh

      - name: Check Cluster Mesh
        run: |
          check-cilium-clustermesh -test.v
          for f in $(ls /tmp/client-*.log)
          do
              echo $f
              cat $f
              echo ""
          done

      - uses: pulumi/actions@v5
        with:
          work-dir: ${{ matrix.dir }}
          command: destroy
          stack-name: dev
          cloud-url: file://~
