name: Pulumi
env:
  PULUMI_CONFIG_PASSPHRASE: ""
  CLUSTER_NUMBER: "5"
on:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - '*/README.md'
jobs:
  kind-clustermesh:
    strategy:
      fail-fast: false
      matrix:
        dir:
          - ./kind-clustermesh
          - ./kind-clustermesh-optimization
    name: Cluster Mesh Kind
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ matrix.dir }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python ✨
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Clean disk
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          cache: true
          go-version: '^1.23.0'

      - name: Install new cilium cli
        run: |
          git clone https://github.com/littlejo/cilium.git
          cd cilium
          git checkout cilium-cli-clustermesh-remote-contexts
          cd cilium-cli
          make
          sudo make install

      - name: Installing dependencies 📦️
        run: pip install -r requirements.txt

      - uses: pulumi/actions@v5

      - name: Create stack
        run: pulumi login --local && pulumi stack init dev && pulumi config set --stack dev clusterNumber $CLUSTER_NUMBER

      - uses: pulumi/actions@v5
        with:
          work-dir: ${{ matrix.dir }}
          command: up
          stack-name: dev
          cloud-url: file://~

      - name: Install cilium connection
        run: |
          CONTEXTD=""
          for i in $(seq 2 $CLUSTER_NUMBER)
          do
            CONTEXTD=$CONTEXTD,kind-cmesh$i
          done
          cilium clustermesh connect --context=kind-cmesh1 --destination-contexts=$CONTEXTD

      - name: Check Cluster Mesh
        run: |
          for i in $(seq 1 $CLUSTER_NUMBER)
          do
            echo "Cluster: kind-cmesh$i"
            cilium status --context=kind-cmesh$i --wait
            cilium clustermesh status --context=kind-cmesh$i --wait
          done
            echo "Cluster Connectivity test kind-cmesh1 and kind-cmesh2"
          cilium connectivity test --context kind-cmesh1 --multi-cluster kind-cmesh2

      - uses: pulumi/actions@v5
        with:
          work-dir: ${{ matrix.dir }}
          command: destroy
          stack-name: dev
          cloud-url: file://~
